/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SparePartsRouteImport } from './routes/spare-parts'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as TechniciansIndexRouteImport } from './routes/technicians.index'
import { Route as TechniciansIdRouteImport } from './routes/technicians.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartsRoute = SparePartsRouteImport.update({
  id: '/spare-parts',
  path: '/spare-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const TechniciansIndexRoute = TechniciansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechniciansRoute,
} as any)
const TechniciansIdRoute = TechniciansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TechniciansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/spare-parts': typeof SparePartsRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/technicians/$id': typeof TechniciansIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/spare-parts': typeof SparePartsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/technicians/$id': typeof TechniciansIdRoute
  '/customers': typeof CustomersIndexRoute
  '/technicians': typeof TechniciansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/spare-parts': typeof SparePartsRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/technicians/$id': typeof TechniciansIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/bookings'
    | '/customers'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/service-areas'
    | '/services'
    | '/settings'
    | '/spare-parts'
    | '/technicians'
    | '/customers/$id'
    | '/technicians/$id'
    | '/customers/'
    | '/technicians/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/bookings'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/service-areas'
    | '/services'
    | '/settings'
    | '/spare-parts'
    | '/customers/$id'
    | '/technicians/$id'
    | '/customers'
    | '/technicians'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/bookings'
    | '/customers'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/service-areas'
    | '/services'
    | '/settings'
    | '/spare-parts'
    | '/technicians'
    | '/customers/$id'
    | '/technicians/$id'
    | '/customers/'
    | '/technicians/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  BookingsRoute: typeof BookingsRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SparePartsRoute: typeof SparePartsRoute
  TechniciansRoute: typeof TechniciansRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-parts': {
      id: '/spare-parts'
      path: '/spare-parts'
      fullPath: '/spare-parts'
      preLoaderRoute: typeof SparePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/technicians/': {
      id: '/technicians/'
      path: '/'
      fullPath: '/technicians/'
      preLoaderRoute: typeof TechniciansIndexRouteImport
      parentRoute: typeof TechniciansRoute
    }
    '/technicians/$id': {
      id: '/technicians/$id'
      path: '/$id'
      fullPath: '/technicians/$id'
      preLoaderRoute: typeof TechniciansIdRouteImport
      parentRoute: typeof TechniciansRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface TechniciansRouteChildren {
  TechniciansIdRoute: typeof TechniciansIdRoute
  TechniciansIndexRoute: typeof TechniciansIndexRoute
}

const TechniciansRouteChildren: TechniciansRouteChildren = {
  TechniciansIdRoute: TechniciansIdRoute,
  TechniciansIndexRoute: TechniciansIndexRoute,
}

const TechniciansRouteWithChildren = TechniciansRoute._addFileChildren(
  TechniciansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  BookingsRoute: BookingsRoute,
  CustomersRoute: CustomersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SparePartsRoute: SparePartsRoute,
  TechniciansRoute: TechniciansRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
